### ISSUE TITLE
Sparrow tests are failing on OSX Yosemite

### ISSUE THREAD

**Issue by dsci** [GateprotectGmbH/sparrow#20]
Sparrow tests are failing on OSX Yosemite with Ruby 2.1.7:

```
rake 

Successfully installed rails-3.2.17
Parsing documentation for rails-3.2.17
Done installing documentation for rails after 0 seconds
1 gem installed
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies....
Using rake 10.4.2
Using i18n 0.7.0
Using multi_json 1.11.2
Using activesupport 3.2.17
Using builder 3.0.4
Using activemodel 3.2.17
Using erubis 2.7.0
Using journey 1.0.4
Using rack 1.4.7
Using rack-cache 1.5.1
Using rack-test 0.6.3
Using hike 1.2.3
Using tilt 1.4.1
Using sprockets 2.2.3
Using actionpack 3.2.17
Using mime-types 1.25.1
Using polyglot 0.3.5
Using treetop 1.4.15
Using mail 2.5.4
Using actionmailer 3.2.17
Using arel 3.0.3
Using tzinfo 0.3.46
Using activerecord 3.2.17
Using activeresource 3.2.17
Using bundler 1.10.6
Using coderay 1.1.0
Using cp-sparrow 0.0.14 from source at .
Using diff-lcs 1.2.5
Using json 1.8.3
Using method_source 0.8.2
Using slop 3.6.0
Using pry 0.10.3
Using rack-ssl 1.3.4
Using rdoc 3.12.2
Using thor 0.19.1
Using railties 3.2.17
Using rails 3.2.17
Using rspec-support 3.4.1
Using rspec-core 3.4.1
Using rspec-expectations 3.4.0
Using rspec-mocks 3.4.0
Using rspec 3.4.0
Using rspec-its 1.2.0
Bundle complete! 9 Gemfile dependencies, 43 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
.F.F..................FF...F...........F......F................

Failures:

  1) camel caser middleware accept header is not given did not convert lower camelcase to underscore params
     Failure/Error: expect(subject["keys"]).to include("userName")
       expected ["user_name", "bar", "lord_foo"] to include "userName"
     # ./spec/integration/rack/camel_caser_spec.rb:41:in `block (3 levels) in <top (required)>'

  2) sparrow middleware reactions when encountering error status the reaction on a server error delegates the error response without failing
     Failure/Error: expect(last_response.status).to eq json[:error_code]

       expected: 507
            got: 500

       (compared using ==)
     # ./spec/integration/rack/error_spec.rb:14:in `block (3 levels) in <top (required)>'

  3) camel caser middleware for Rails accept header is not given convert input params did not convert lower camelcase to underscore params
     Failure/Error: expect(subject["keys"]).to include("userName")
       expected ["user_name", "last_name", "bar", "lord_füü", "de"] to include "userName"
     # ./spec/integration/rails/camel_caser_spec.rb:189:in `block (4 levels) in <top (required)>'

  4) camel caser middleware for Rails accept header is not given convert input params did not convert all UPPERCASE words to underscore params
     Failure/Error: expect(subject["keys"]).to include("DE")
       expected ["user_name", "last_name", "bar", "lord_füü", "de"] to include "DE"
     # ./spec/integration/rails/camel_caser_spec.rb:194:in `block (4 levels) in <top (required)>'

  5) camel caser middleware for Rails accept header is not given the reaction on error responses does not touch the response if a server error gets triggered
     Failure/Error:
       expect do
         get '/error', {}, { 'CONTENT-TYPE' => 'application/json' }
       end.to raise_error ZeroDivisionError

       expected ZeroDivisionError, got #<ActionController::RoutingError: uninitialized constant ErrrosController> with backtrace:
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/activesupport-3.2.17/lib/active_support/inflector/methods.rb:230:in `block in constantize'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/activesupport-3.2.17/lib/active_support/inflector/methods.rb:229:in `each'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/activesupport-3.2.17/lib/active_support/inflector/methods.rb:229:in `constantize'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/actionpack-3.2.17/lib/action_dispatch/routing/route_set.rb:69:in `controller_reference'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/actionpack-3.2.17/lib/action_dispatch/routing/route_set.rb:54:in `controller'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/actionpack-3.2.17/lib/action_dispatch/routing/route_set.rb:32:in `call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/actionpack-3.2.17/lib/action_dispatch/routing/route_set.rb:608:in `call'
         # ./lib/sparrow/response_middleware.rb:11:in `call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/actionpack-3.2.17/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/rack-1.4.7/lib/rack/etag.rb:23:in `call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/rack-1.4.7/lib/rack/conditionalget.rb:25:in `call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/actionpack-3.2.17/lib/action_dispatch/middleware/head.rb:14:in `call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/actionpack-3.2.17/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/actionpack-3.2.17/lib/action_dispatch/middleware/flash.rb:242:in `call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:210:in `context'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:205:in `call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/actionpack-3.2.17/lib/action_dispatch/middleware/cookies.rb:341:in `call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/actionpack-3.2.17/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:405:in `_run__3022752445930787329__call__3991858485286818680__callbacks'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:405:in `__run_callback'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:81:in `run_callbacks'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/actionpack-3.2.17/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/actionpack-3.2.17/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/actionpack-3.2.17/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/actionpack-3.2.17/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
         # ./lib/sparrow/middleware.rb:33:in `call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/railties-3.2.17/lib/rails/rack/logger.rb:32:in `call_app'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/railties-3.2.17/lib/rails/rack/logger.rb:16:in `block in call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/activesupport-3.2.17/lib/active_support/tagged_logging.rb:22:in `tagged'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/railties-3.2.17/lib/rails/rack/logger.rb:16:in `call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/actionpack-3.2.17/lib/action_dispatch/middleware/request_id.rb:22:in `call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/rack-1.4.7/lib/rack/methodoverride.rb:21:in `call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/rack-1.4.7/lib/rack/runtime.rb:17:in `call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/activesupport-3.2.17/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/rack-1.4.7/lib/rack/lock.rb:15:in `call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/actionpack-3.2.17/lib/action_dispatch/middleware/static.rb:63:in `call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/railties-3.2.17/lib/rails/engine.rb:484:in `call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/railties-3.2.17/lib/rails/application.rb:231:in `call'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/railties-3.2.17/lib/rails/railtie/configurable.rb:30:in `method_missing'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
         # /Users/Demo/.rvm/gems/ruby-2.1.7@sparrow/gems/rack-test-0.6.3/lib/rack/test.rb:58:in `get'
         # ./spec/integration/rails/camel_caser_spec.rb:243:in `block (5 levels) in <top (required)>'
         # ./spec/integration/rails/camel_caser_spec.rb:242:in `block (4 levels) in <top (required)>'
     # ./spec/integration/rails/camel_caser_spec.rb:242:in `block (4 levels) in <top (required)>'

  6) Sparrow::Configuration default_json_request_key_transformation_strategy should eq :camelize
     Failure/Error: is_expected.to eq :camelize

       expected: :camelize
            got: :underscore

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -:camelize
       +:underscore
     # ./spec/unit/configuration_spec.rb:12:in `block (2 levels) in <module:Sparrow>'

  7) Sparrow::Configuration default_json_key_transformation_strategy should eq :camelize
     Failure/Error: expect(actual).to eq :camelize

       expected: :camelize
            got: :underscore

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -:camelize
       +:underscore
     # ./spec/unit/configuration_spec.rb:46:in `block (3 levels) in <module:Sparrow>'

Finished in 0.70305 seconds (files took 0.20937 seconds to load)
63 examples, 7 failures

Failed examples:

rspec ./spec/integration/rack/camel_caser_spec.rb:39 # camel caser middleware accept header is not given did not convert lower camelcase to underscore params
rspec ./spec/integration/rack/error_spec.rb:13 # sparrow middleware reactions when encountering error status the reaction on a server error delegates the error response without failing
rspec ./spec/integration/rails/camel_caser_spec.rb:187 # camel caser middleware for Rails accept header is not given convert input params did not convert lower camelcase to underscore params
rspec ./spec/integration/rails/camel_caser_spec.rb:192 # camel caser middleware for Rails accept header is not given convert input params did not convert all UPPERCASE words to underscore params
rspec ./spec/integration/rails/camel_caser_spec.rb:241 # camel caser middleware for Rails accept header is not given the reaction on error responses does not touch the response if a server error gets triggered
rspec ./spec/unit/configuration_spec.rb:11 # Sparrow::Configuration default_json_request_key_transformation_strategy should eq :camelize
rspec ./spec/unit/configuration_spec.rb:44 # Sparrow::Configuration default_json_key_transformation_strategy should eq :camelize
```

**Comment by anmuel** [comment]
Should work out again now. The failures occurred because of the changed default request transformation strategy which was changed by request from camelizing to underscoring.
